### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by pfmaggi**
* Update WindowManager version to latest alpha.
* Update Kotlin version
* Update viewbinding syntax

### CODE REVIEW

**Review by kford55 — APPROVED** [review]
:+1:

**Comment by pfmaggi** [comment]
Thanks @kford55, can you also approve the PR?

**Comment by kford55** [comment]
LGTM

**Comment by kford55** [comment]
I did, I don't have write access it seems

**Review by kford55 — APPROVED** [review]
Approved

**Review by keyboardsurfer — APPROVED** [review]

**Pull request merged**
