### PR TITLE
Create android.yml

### PR DESCRIPTION
**Pull request by gitwdel**
user-interface-samples-slice-viewer-v1.0.1.zip

### CODE REVIEW

**Comment by Wdel06** [comment]
127

**Comment by Wdel06** [comment]
127

**Comment by Wdel06** [comment]
#138

**Comment by Wdel06** [comment]
#137

**Comment by Wdel06** [comment]
Wdel06:master

**Comment by Wdel06** [comment]
#136

**Comment by gitwdel** [comment]
#139

**Pull request closed without merging**
