### PR TITLE
[ImmersiveMode] Update to Android 12 DP1

### PR DESCRIPTION
**Pull request by yaraki**
Change-Id: I4ea4e8f8fd21b0e55a030d8641e8713db8335044

### CODE REVIEW

**Comment by yaraki** [comment]
I got review from the engineering team internally.

**Review by chrisbanes — APPROVED** [review]
LGTM, but I think we should keep these changes in a branch until S is final. WDYT?

**Comment by yaraki** [comment]
Let's make a branch for that. What should it be called? `s-dp`, maybe?

**Comment by chrisbanes** [comment]
Yeah, how about `dev-androidS`?

**Comment by yaraki** [comment]
Created `dev-androidS` and rebased the PR.

**Comment by chrisbanes** [comment]
LGTM, 🚢

**Pull request merged**
